### ISSUE TITLE
Assertion Error Please  help

### ISSUE THREAD

**Issue by moohpooh2001** [arbalet-project/arbapps#6]
Please help. I use Ubuntu 14 and Arduino IDE 1.6.11 but there is assertionError as below. I try many ways, but don't work.

mooh@mooh-Inspiron-1464:~/Arbalet/arbapps/ColorDemonstrator$ python Colordemonstrator.py -w
Font /usr/share/fonts/truetype/freefont/FreeSans.ttf of size 4
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/arbalet-0.0.1-py2.7.egg/arbasdk/arbalink.py", line 188, in run
    self.connect_forever()
  File "/usr/local/lib/python2.7/dist-packages/arbalet-0.0.1-py2.7.egg/arbasdk/arbalink.py", line 76, in connect_forever
    success = self.connect()
  File "/usr/local/lib/python2.7/dist-packages/arbalet-0.0.1-py2.7.egg/arbasdk/arbalink.py", line 67, in connect
    self.handshake()
  File "/usr/local/lib/python2.7/dist-packages/arbalet-0.0.1-py2.7.egg/arbasdk/arbalink.py", line 117, in handshake
    assert version == self.PROTOCOL_VERSION, "Hardware uses protocol v{}, SDK uses protocol v{}".format(version, self.PROTOCOL_VERSION)
AssertionError: Hardware uses protocol v72, SDK uses protocol v2

**Comment by ymollard** [comment]
This error means that the Arduino board rebooted while handshake was not ended yet.
What Arduino board are you using? Does it happen every single time? Have you tried keeping python running and plugging/unplugging the Arduino until connection is successful? Arbalink will complain that the device does not exist when unplugged, but will keep trying to connect.
I used to have this issue with Arduino Uno only, but it was happening only from time to time. Now solved by increasing a bit more the timeouts. Especially [that one](https://github.com/arbalet-project/arbasdk/blob/master/hardware/arduino/Arbalet/examples/Arbalink/Arbalink.ino#L41), but 5000 is already high though. Try, say, up to 10000ms.

**Comment by moohpooh2001** [comment]
Thank you so much for your respond. Yes, I use Arduino Uno. This problem
occured after I changed the metrix to  50 LEDS in config150.json and also
config150touch.json. Then I setup abasdk again.
Sorry, I did not tell you. I would try again as your advice.
Thank you

**Comment by ymollard** [comment]
Could you show your configuration file after your changes? (e.g. fork arbasdk on github and commit/push your changes there). 
Have you been using [the helper script](https://github.com/arbalet-project/arbasdk/blob/master/notebooks/generate_mapping.ipynb) to generate it? Just sprcify the geometry (say width = 5, height = 10 for instance) and it will create a config50.json It won't override config150 so make sure you are actually using that file afterwards.
If it was working before your changes then my tip about timeouts won't suit. Arduino might reboot  ending up to this error if the configuration is broken.

**Comment by moohpooh2001** [comment]
Yes, this is my file changed.
{
 "leds_pin_number": 12,
 "devices": {
   "unix": ["/dev/ttyACM0", "/dev/ttyACM1"],
   "windows": ["COM11", "COM12"]
 },
 "refresh_rate": 50,
 "speed": 115200,
 "mapping":
   [[4, 5, 14, 15, 24, 25, 34, 35, 44, 45],
    [3, 6, 13, 16, 23, 26, 33, 36, 43, 46],
    [2, 7, 12, 17, 22, 27, 32, 37, 42, 47],
    [1, 8, 11, 18, 21, 28, 31, 38, 41, 48],
    [0, 9, 10, 19, 20, 29, 30, 39, 40, 49]],
   "font": "freesans",
   "vertical": true,
   "touch": {
     "num_keys": 12,
     "threshold": 30,
     "calibrated": true,
     "window_size": 8,
     "keys": [[[14, 8], [14, 9]],
              [[14, 6], [14, 7]],
              [[14, 5], [14, 4]],
              [[14, 3], [14, 2]],
              [[14, 1], [14, 0]],
              [[11, 4], [11, 5]]],
      "mapping": {
        "bidirectional": ["right", "right", "none", "left", "left", "none"],
        "tridirectional": ["right", "right", "none", "left", "left", "up"],
        "quadridirectional": ["right", "none", "down", "none", "left",
"up"],
        "columns": [5, 4, 3, 2, 1, "none"],
        "individual": [1, 2, 3, 4, 5, 6]},
     "colors": {
       "active":   [150, 150, 150],
       "inactive": [10, 10, 10]}
   }
 }

Thank you for your suggestion. I don't know that it can generate config
file, I am new in all (python and ubuntu). So I should use the notebooks ?
I'll try. Thank you so much.

**Comment by ymollard** [comment]
I'm pretty sure you used this configuration file without plugging a MPR121 sensor to your Arduino. If this is the case disable the touch interface with:
`"num_keys": 0,`
And setup again.
The rest of the file seems correct so you don't have to use the notebook that is tthere only for convenience.

**Comment by moohpooh2001** [comment]
Yes, now success. Thank you for your help. I'll try with more LEDs.
😄😄

**Comment by ymollard** [comment]
I'll make this mistake clearer un the future.

**Comment by jblx** [comment]
Please help. I use Window and Arduino IDE 1.6.5.And the hardware is arduino mega 2560. But there is assertion Error as below. I try many ways, but don't work.$  python -m arbalet.apps.tetris -w
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
GAME OVER
('You scored', 0)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\site-packages\arbalet\core\link\abstract.py", line 71, in run
    self.connect_forever()
  File "c:\python27\lib\site-packages\arbalet\core\link\abstract.py", line 38, in connect_forever
    self.connect()
  File "c:\python27\lib\site-packages\arbalet\core\link\arduino.py", line 55, in connect
    self.handshake()
  File "c:\python27\lib\site-packages\arbalet\core\link\arduino.py", line 97, in handshake
    assert version == self.PROTOCOL_VERSION, "Hardware uses protocol v{}, SDK uses protocol v{}".format(version, self.PROTOCOL_VERSION)
AssertionError: Hardware uses protocol v72, SDK uses protocol v2
I really really need help . Please help me .

**Comment by jblx** [comment]
I use Window 10

**Comment by ymollard** [comment]
@jblx Your Arduino is sending a "Hello" message endlessly but communication between Python and Arduino can't be established.

Can you modify the Arduino sketch [here](https://github.com/arbalet-project/arbasdk/blob/master/hardware/arduino/Arbalet/examples/Arbalink_WS2812B/Arbalink_WS2812B.ino#L86) with 
`char c = read_char(); if(c!=CMD_HELLO) {write_char(c):  return false; }`

By this way the assertion error will likely happen again, but instead of `v72` (72 means 'H' in ASCII encoding) it should display the character received by Arduino. If it's 0 (i.e. you see `v0`) it might be a timeout because serial connection failed.

**Comment by ymollard** [comment]
@jblx What branch are you using? `dev` or `master`?

**Comment by ymollard** [comment]
@jblx What's inside your [default.cfg](https://github.com/arbalet-project/arbasdk/blob/master/arbalet/config/default.cfg) and inside the *.json file named in `config:`?
Have you tried to change anything in the configuration or did you just clone the git repo and execute the code?
